name: Test, build, deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
  workflow_dispatch:
    inputs:
      build_executable:
        description: 'Build Windows executable'
        type: boolean
        default: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-path: 'uv.lock'

      - name: Create virtual environment
        run: uv venv

      - name: Generate lock file
        run: uv pip compile pyproject.toml -o uv.lock

      - name: Install dependencies
        run: uv pip install -r pyproject.toml -e .

      - name: Run Basedpyright
        run: |
          .venv/bin/python -m basedpyright

  build-executable:
    runs-on: windows-latest

    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          cache-dependency-path: 'uv.lock'

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          uv pip install -r pyproject.toml -e .
          uv pip install pyinstaller

      - name: Build executable using spec file
        run: |
          .venv\Scripts\python.exe -m PyInstaller pyplayer.spec --distpath dist
        shell: cmd

      - name: Zip executable
        run: Compress-Archive -Path dist\pyplayer.exe,README.md -DestinationPath dist\pyplayer-windows.zip
        shell: pwsh

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: pyplayer-windows
          path: dist\pyplayer-windows.zip
