name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    needs: build-executable
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: pyplayer-windows
          path: dist
          extract: false

      - name: Rename artifact
        run: |
          mv dist/pyplayer-windows.zip dist/pyplayer-windows-${{ github.ref_name }}.zip
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          draft: true
          prerelease: ${{ contains(github.ref_name, '-beta') }}
          body: |
            / notes here /

            **For windows users:**
            Download the zip file called "**pyplayer-windows-${{ github.ref_name }}.zip**". Use it in your terminal, or you can add it to your path so you can use it from anywhere!

          artifacts: dist/pyplayer-windows-${{ github.ref_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
