name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-executable:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          uv pip install -e .
          uv pip install pyinstaller

      - name: Build executable
        run: |
          .venv\Scripts\python.exe -m PyInstaller --onefile --name pyplayer --add-data "pyplayer;pyplayer" pyplayer\__init__.py
        shell: cmd

      - name: Zip executable
        run: Compress-Archive -Path dist\pyplayer.exe -DestinationPath dist\pyplayer-windows.zip
        shell: pwsh

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: pyplayer-windows
          path: dist\pyplayer-windows.zip

  create-release:
    runs-on: ubuntu-latest
    needs: build-executable
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: pyplayer-windows
          path: dist

      - name: Rename artifact
        run: |
          mv dist/pyplayer-windows.zip dist/pyplayer-windows-${{ github.ref_name }}.zip
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          draft: true
          prerelease: ${{ contains(github.ref_name, '-beta') }}
          body: |
            / notes here /

            **For windows users:**
            Download the zip file called "**pyplayer-windows-${{ github.ref_name }}.zip**". Use it in your terminal, or you can add it to your path so you can use it from anywhere!

          artifacts: dist/pyplayer-windows-${{ github.ref_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
